# Generated by Django 4.0.5 on 2022-06-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_clubadmin_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pictures',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
