# Generated by Django 4.0.5 on 2022-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_members'),
        ('accounts', '0003_profile_profile_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clubs',
            field=models.ManyToManyField(to='clubs.club'),
        ),
    ]
