# Generated by Django 4.0.5 on 2022-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_clubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pictures',
            new_name='profile_picture',
        ),
    ]
