# Generated by Django 4.0.5 on 2022-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_post_like_count'),
        ('accounts', '0005_rename_profile_pictures_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='clubs.post'),
        ),
    ]
