# Generated by Django 4.0.5 on 2022-06-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
    ]
