# Generated by Django 4.0.5 on 2022-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
