# Generated by Django 4.0.5 on 2022-06-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attendee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ParticipationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.post')),
            ],
        ),
    ]
